databases:
  - name: akvrix-db
    plan: free
    databaseName: akvrix_db
    user: akvrix_user

services:
  - type: web
    name: akvrix
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn akvrix_project.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: akvrix-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.12.0"
