services:
  - type: web
    name: akvrix
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn akvrix_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://akvrix.onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.0"
